### ISSUE TITLE
Proofs for simple lambda identity expressions

### ISSUE THREAD

**Issue by gtrepta** [runtimeverification/plutus-core-semantics#220]
Work has begun on the [`proof-examples`](https://github.com/runtimeverification/plutus-core-semantics/tree/proof-examples) branch to develop proofs for K-Plutus.

The three claims that we aim to prove are:
```
  claim <k> [ ( lam v_0 v_0 ) (con integer 1) ] => < con integer 1 > ... </k>
  claim <k> [ ( lam v_0 v_0 ) (con TN:TypeConstant C:Constant) ] => < con TN C > ... </k>
  claim <k> [ ( lam X:UplcId X ) T:Term] =>  T  ... </k>
```

**Comment by gtrepta** [comment]
The initial commit https://github.com/runtimeverification/plutus-core-semantics/commit/50dc30e17788600853c046d58b5c49177cd63d6c is using the wrong expression on the right hand side of the rewrites. The terms in parentheses should be in angle brackets instead.

**Comment by ChristianoBraga** [comment]
We should run `make test-prove` and `.build/usr/bin/kplc prove --directory simple-proofs/verification/haskell simple-proofs/simple-symbolic.md --debugger --debug-script k-script`.

Inside the repl, `prove 5` and `step n` for some sufficient `n` like 10.

While trying to prove the first claim, we reached a state where the prover didn't know if `x` was in the environment or not. This could be solved in different ways, including:
1. Having auxiliar claims saying what to do on each case. Then each claim (when `x` is in the environment and otherwise) must be proven separetely.   
2. Change the semantic rule with two rules specifying application on each case.
3. Implement the semantics for `#push` as a single rule using `#if`.

**Comment by SchmErik** [comment]
Additional learning notes:

```
claim <k> [ ( lam v_0 v_0 ) (con integer 1) ] => < con integer 1 > ... </k>
```
This claim got stuck in the #push function.
```
rule #push(E:Map, X:UplcId, I:Int) => E[X <- ({E[X]}:>List ListItem(I))]
requires X in_keys(E)
rule #push(E:Map, X:UplcId, I:Int) => E[X <- ListItem(I)] [owise]
```
This definition for `#push` causes branching and results in a stuck state. The solution to this is to rewrite the functional rule as following:
```
rule #push(E:Map, X:UplcId, I:Int) =>
     #if X in_keys(E)
     #then E[X <- #append({E[X]}:>List, I)]
     #else E[X <- ListItem(I)]
     #fi
```

**Comment by SchmErik** [comment]
Virgil's suggestions:
```
1 define ceil({@L}:>List)
2 use allValuesAreList in the requires clause of the claim
3 (most likely) rule isList(Rho[V]) => true requires V in_keys(Rho) andBool allValuesAreList(Tho)
ceil({@L}:>List) => isList(@L) andBool #ceil(@L)
MySort => isMySort
```

**Comment by ChristianoBraga** [comment]
> > We tried 1 and 3. They lead to some definedness problems for projection functions including for `{@L:Kitem}:>List`, solved by the rule below added to `UPLC-ENVIRONMENT`:
> > ```
> > rule #Ceil({@L:KItem}:>List) => {isList(@L) #Equals true} #And #Ceil(@L)  [anywhere, simplification]
> > ```
> 
> One question that was brought up: why are we having to write these ceil rules manually? shouldn't they be injected automatically by kompile?

Exactly! At least with respect to K’s builtins. I would understand having to define them for whatever a user’s definition create. So which is the methodology for adding definedness rules?

**Comment by gtrepta** [comment]
```
  rule <k> V:Value ~> [ < lam X:UplcId M:Term RHO:Map > _] => M ... </k>
       <env> _ => #push( RHO, X, #uplcHash(V) ) </env>
       <heap> Heap => Heap[ #uplcHash(V) <- V ] </heap>
```

This rule is causing an issue with the haskell backend because of the `#push` on the RHS. I don't recall exactly what @virgil-serbanuta said was the problem, I think it was something about the backend dropping the case where the RHS is undefined?

**Comment by ChristianoBraga** [comment]
I think an additional constraint was being added to the proof, saying that `X` should be in `in_keys(RHO)`.

**Comment by virgil-serbanuta** [comment]
Yes, the problem is that, in principle, when you apply this rule, you start with a configuration without any constraint and you end up with a configuration in which `X in_keys(RHO)` (I also think that this was the constraint, but I don't fully remember). So, this rule basically says "if X is not in_keys(RHO)" then everything is fine, let's just ignore the configuration and the corresponding proof branch.
