### ISSUE TITLE
Implement the factorial function using Y combinator in UPLC "by hand"

### ISSUE THREAD

**Issue by ChristianoBraga** [runtimeverification/plutus-core-semantics#229]
Instead of using the output f the Plutus Tx  compiler it seems to be simpler to write our own function first.

**Comment by SchmErik** [comment]
@gtrepta I've been flipping through the book "Type and Programming Languages" by Benjamin Pierce and there's a definition of factorial on page 66 using a language that's similar to uplc. Recursion and fixed point combinator is defined on page 65

**Comment by SchmErik** [comment]
Also, I found this to be a helpful presentation that leads the viewer through an exercise: https://www.youtube.com/watch?v=9T8A89jgeTI&ab_channel=Computerphile
The textbook reference tells you the answer right away and I felt that I learned more by going through this video.

**Comment by SchmErik** [comment]
This is my current solution but it seems to get stuck in some sort of infinite loop:
```
(program 1.0.0
    [
        ( lam f [
              (lam x [ f ( lam y [ x x y ] ) ] )
              (lam x [ f ( lam y [ x x y ] ) ] )
        ])
        ( lam f_1 ( lam n_0
          [ (force ( builtin ifThenElse ) )
            [ [ ( builtin equalsInteger ) ( con integer 0 ) ] n_0 ] (con integer 1)
            [ f_1 [ (builtin subtractInteger) n_0 (con integer 1) ]]
          ]
        ))
        ( con integer 0)
    ]
)
```

**Comment by gtrepta** [comment]
Here's mine
```
(program 1.0.0
  [ (lam f [(lam x [f (lam y [x x y])]) (lam x [f (lam y [x x y])])]) // Y-combinator
    (lam fct
      (lam n [ (force (builtin ifThenElse))
               [ (builtin equalsInteger) (con integer 0) n ]
                 (con integer 1)
               [ (builtin multiplyInteger) n [ fct [ (builtin subtractInteger) n (con integer 1) ] ] ]
             ]
      )
    )
    (con integer 3)
  ]
)
```

I also run into the infinite looping, and the issue is that it's evaluating the second branch of the `ifThenElse` builtin before returning the result of the builtin's expression, so it nests infinitely into it. I'm wondering if there's a force/delay that can go somewhere, or if the Y-combinator is the wrong construct to be using (I remember @ChristianoBraga mentioning that a different fixed-point might be better suited for this).

**Comment by ChristianoBraga** [comment]
Yes I think there are two aspects we need to take into account when
choosing the fixpont: (i) strictness lazy mess and (ii) dynamic x static
binding. UPLC is strict and has static binding.

Em qua., 22 de jun. de 2022 às 23:02, gtrepta ***@***.***>
escreveu:

**Comment by ChristianoBraga** [comment]
Maybe this
https://www.cs.cornell.edu/courses/cs3110/2012sp/lectures/lec29-fixpoints/lec29.html
can shed some light. I will read it right after the K planning meeting.

**Comment by gtrepta** [comment]
After a discussion with @SchmErik we uncovered a solution using force/delay:
```
(program 1.0.0
  [ (lam f [(lam x [f (lam y [x x y])]) (lam x [f (lam y [x x y])])])
    (lam fct
      (lam n (force [ (force (builtin ifThenElse))
                      [ (builtin equalsInteger) (con integer 0) n ]
             (delay     (con integer 1))
             (delay   [ (builtin multiplyInteger) n [ fct [ (builtin subtractInteger) n (con integer 1) ] ] ])
                    ]
             )
      )
    )
    (con integer 10)
  ]
)
```

This works properly, and the reason is that since each branch of the `ifThenElse` is inside a delay, the uplc semantics wont try to evaluate it until the `ifThenElse` gets evaluated first, and then the force on the outside of the whole `ifThenElse` expression will operate on whichever delayed branch comes out.

**Comment by SchmErik** [comment]
@gtrepta and @ChristianoBraga I ran this solution on both uplc and kplc and they produced matching results.

**Comment by gtrepta** [comment]
Does the example that loops indefinitely on kplc do the same thing on uplc?

**Comment by gtrepta** [comment]
Here's a curious example where lambda/unit are used in place of delay/force (also some rearranging so the application of the factorial function is at the head of the program):
```
(program 1.0.0
  [ (lam factorial [ factorial (con integer 10) ])
    [ (lam f [(lam x [f (lam y [x x y])]) (lam x [f (lam y [x x y])])])
      (lam fct
        (lam n [
                 [ (force (builtin ifThenElse))
                        [ (builtin equalsInteger) (con integer 0) n ]
                          (lam wait (con integer 1))
                          (lam wait [ (builtin multiplyInteger) n [ fct [ (builtin subtractInteger) n (con integer 1) ] ] ])
                 ]
                 (con unit ())
               ]
        )
      )
    ]
  ]
)
```

**Comment by SchmErik** [comment]
I had this thought: is it possible to replace non polymorphic use of `(force T)` with `[ (lam go [ go go] ) T]` and `(delay T)` with `(lam wait T)`? So I translated the factorial function in https://github.com/runtimeverification/plutus-core-semantics/issues/229#issuecomment-1164787785 with this substitution and it worked.

In terms of space in the flat format, `(delay T)` is actually equivalent to `(lam wait T)` but `(force T)` is much smaller than `[ (lam go [ go go ] T]`.  Here's a break down:

`(lam wait T)` is 4 bits + SizeOf(T) in flat (note, wait is not encoded in this expression because flat uses de Bruijin indicies.
`(delay T)` is 4 bits + SizeOf(T) in flat. So they're equivalent

Now onto `(force ... )`
`(force T)` is 4 bits + SizeOf(T)

`[ (lam go [go go]) T ]` is 4 bits (application) + 4 bits (lam) + 4 bits (inner application) + 4 bits (variable) + 8 bits (go) + 4 bits (variable) + 8 bits (second go) + sizeOf(T) => 40 bits + sizeOf(T) so you save 36 bits. I've seen `[ (lam go [go go] T ]` a lot in our examples.
```
(program 1.0.0

  [ (lam f [(lam x [f (lam y [x x y])]) (lam x [f (lam y [x x y])])])
    (lam fct
      (lam n [ (lam go [ go go ])
               [ (force (builtin ifThenElse))
                 [ (builtin equalsInteger) (con integer 0) n ]
                 ( lam wait (con integer 1) )
                 ( lam wait
                   [ (builtin multiplyInteger)
                     n
                     [ fct [ (builtin subtractInteger) n (con integer 1) ] ]
                   ]
                 )
               ]
             ]
      )
    )
    (con integer 10)
  ]
)
```

**Comment by gtrepta** [comment]
Here's an example done in continuation passing style. The examples above build a string of multiplication operations on all of the numbers in the factorial and folds over it at the end. The function below multiplies each number as it iterates through them.
```
(program 1.0.0
  [ (lam factorial [ factorial (con integer 10) ])
    [ (lam factorialAux (lam n [ factorialAux n (con integer 1) ]))
      [ (lam f [(lam x [f (lam y [x x y])]) (lam x [f (lam y [x x y])])])
        (lam fct
          (lam n
            (lam cont
              (force [ (force (builtin ifThenElse))
                       [ (builtin equalsInteger) (con integer 0) n ]
              (delay   cont)
              (delay   [ fct [ (builtin subtractInteger) n (con integer 1) ] [ (builtin multiplyInteger) n cont ] ])
                     ]
              )
            )
          )
        )
      ]
    ]
  ]
)
```
