### ISSUE TITLE
Investigate how to `uplc` for running programs, and using their program generator for tests

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/plutus-core-semantics#51]
Instructions here about:

- How to run `uplc`, and
- How to generate tests using their NEAT test generator.

**Comment by SchmErik** [comment]
Steps to build/run uplc:

1. Clone the plutus repo [https://github.com/input-output-hk/plutus](url) and `cd plutus/`.
2. To build `uplc`: run `nix-shell & cabal build plutus-core` from the root directory of the plutus repo
3. The executable is generated in the `dist-newstyle` directory. In order to find the executable I ran a find command like so: `find . -type f -name uplc`.

**Comment by SchmErik** [comment]
Steps to build nofib-exec (this program emits untyped plutus code that is run by plutus-benchmark).
1. To build `nofib-exec`: run `nix-shell && cabal build nofib-exec`
2. Find the executable in the `dist-newstyle` directory as mentioned in step 3 of the uplc build step.

**Comment by SchmErik** [comment]
Both tools have the ability to generate and execute test code. Run both tools with the `-h` option to view the options. `uplc` generates smaller programs and `nofib-exec` generates larger programs. Both can run the plutus CEK machine to reduce the terms. I'll go ahead and generate some tests early next week.
